### ISSUE TITLE
open space shootert in nieuwe unity

### ISSUE THREAD

**Issue by InnoCrator** [cortexarts/space-shootert#1]
Opent niet in Unity laatste versie. Wordt geupgrade en doet t daarna niet meer. Kan niet spelen. Ligt aan de versie waarin gebouwd is. Kan je dit allemaal nog eens laden in de nieuwste versie en dan naar git sturen? Denk dat het helpt

**Comment by Feikovandijk** [comment]
Komt door een kleine bug in de gamecontroller en een oude functie met mesh colliders, is hier gefixt: https://github.com/cortexarts/Spaceshooter-unity-5
